name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: test-project

    - name: Build with Gradle
      run: ./gradlew app:assembleDebug
      working-directory: test-project

    - name: Run test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        arch: 'x86_64'
        api-level: 30
        working-directory: test-project
        script: ./gradlew app:connectedDebugAndroidTest

    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-project
        path: ./test-project

  report:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
    - uses: actions/checkout@v3

    - name: Download Test Reports Folder
      uses: actions/download-artifact@v2
      with:
        name: test-project

    - name: Report test result
      uses: ./
